name: mObywatelPreview
options:
  xcodeVersion: "15.4"
targets:
  mObywatelPreview:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: iOS/App/DesignSystemPreview/DesignSystemPreview
    info:
      path: iOS/App/DesignSystemPreview/DesignSystemPreview/Info.plist
